package com.reesby.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="ContactMaster") 
public class Contact { 
	
	private String contactId;
	private String tenantId;
	private String cName;
	private String clientorcandidate;
	private String cEmail;
	private String cWorkph;
	private String cPersonalph;
	private String cCurrrentaddress;
	private String cCommaddress;
	private String cLinkedInurl;
	
	
	@DynamoDBHashKey(attributeName = "contact_id")
	@DynamoDBAutoGeneratedKey
	public String getContactId() {
		return contactId;
	}
	public void setContactId(String contactId) {
		this.contactId = contactId;
	}
	
	@DynamoDBRangeKey(attributeName = "tenant_id")
	public String getTenantId() {
		return tenantId;
	}
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}
	
	@DynamoDBAttribute(attributeName = "cName")
	public String getcName() {
		return cName;
	}
	public void setcName(String cName) {
		this.cName = cName;
	}
	
	@DynamoDBAttribute(attributeName = "clientorcandidate")
	public String getClientorcandidate() {
		return clientorcandidate;
	}
	public void setClientorcandidate(String clientorcandidate) {
		this.clientorcandidate = clientorcandidate;
	}
	
	@DynamoDBAttribute(attributeName = "cEmail")
	public String getcEmail() {
		return cEmail;
	}
	public void setcEmail(String cEmail) {
		this.cEmail = cEmail;
	}
	
	@DynamoDBAttribute(attributeName = "cWorkph")
	public String getcWorkph() {
		return cWorkph;
	}
	public void setcWorkph(String cWorkph) {
		this.cWorkph = cWorkph;
	}
	
	@DynamoDBAttribute(attributeName = "cPersonalph")
	public String getcPersonalph() {
		return cPersonalph;
	}
	public void setcPersonalph(String cPersonalph) {
		this.cPersonalph = cPersonalph;
	}
	
	@DynamoDBAttribute(attributeName = "cCurrrentaddress")
	public String getcCurrrentaddress() {
		return cCurrrentaddress;
	}
	public void setcCurrrentaddress(String cCurrrentaddress) {
		this.cCurrrentaddress = cCurrrentaddress;
	}
	
	@DynamoDBAttribute(attributeName = "cCommaddress")
	public String getcCommaddress() {
		return cCommaddress;
	}
	public void setcCommaddress(String cCommaddress) {
		this.cCommaddress = cCommaddress;
	}

	
	@DynamoDBAttribute(attributeName = "cLinkedInurl")
	public String getcLinkedInurl() {
		return cLinkedInurl;
	}
	public void setcLinkedInurl(String cLinkedInurl) {
		this.cLinkedInurl = cLinkedInurl;
	}

}
