package com.reesby.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="DealMaster") 
public class Deal {
	
	private String dealId;
	private String dealowner;	
	private String dealName;
	private String tenantId;
	private String dBusinessType;	
	private String dContactName;
	private String dAmt;
	private String dClosingdt;
	private String dStatus;
	
	
	@DynamoDBHashKey(attributeName = "Deal_id")
	@DynamoDBAutoGeneratedKey
	public String getDealId() {
		return dealId;
	}
	public void setDealId(String dealId) {
		this.dealId = dealId;
	}
	
	@DynamoDBAttribute(attributeName = "deal_owner")
	public String getDealowner() {
		return dealowner;
	}
	public void setDealowner(String dealowner) {
		this.dealowner = dealowner;
	}
	
	@DynamoDBAttribute(attributeName = "deal_Name")
	public String getDealName() {
		return dealName;
	}
	public void setDealName(String dealName) {
		this.dealName = dealName;
	}
	
	@DynamoDBRangeKey(attributeName = "tenant_id")
	public String getTenantId() {
		return tenantId;
	}
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}
	
	@DynamoDBAttribute(attributeName = "deal_businesstype")
	public String getdBusinessType() {
		return dBusinessType;
	}
	public void setdBusinessType(String dBusinessType) {
		this.dBusinessType = dBusinessType;
	}
	
	@DynamoDBAttribute(attributeName = "deal_ContactName")
	public String getdContactName() {
		return dContactName;
	}
	public void setdContactName(String dContactName) {
		this.dContactName = dContactName;
	}
	
	@DynamoDBAttribute(attributeName = "deal_amount")
	public String getdAmt() {
		return dAmt;
	}
	public void setdAmt(String dAmt) {
		this.dAmt = dAmt;
	}
	
	@DynamoDBAttribute(attributeName = "deal_closingdate")
	public String getdClosingdt() {
		return dClosingdt;
	}
	public void setdClosingdt(String dClosingdt) {
		this.dClosingdt = dClosingdt;
	}
	
	@DynamoDBAttribute(attributeName = "deal_status")
	public String getdStatus() {
		return dStatus;
	}
	public void setdStatus(String dStatus) {
		this.dStatus = dStatus;
	}

}
