package com.reesby.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="LeadMaster") 
public class Lead {
	
	private String leadowner;
	private String leadId;
	private String tenantId;
	private String lCompany;	
	private String lFname;
	private String lLname;
	private String lEmail;
	private String lWorkph;
	private String lPersonalph;
	private String lStatus;

	
	@DynamoDBHashKey(attributeName = "Lead_id")
	@DynamoDBAutoGeneratedKey
	public String getLeadId() {
		return leadId;
	}
	public void setLeadId(String leadId) {
		this.leadId = leadId;
	}
	
	@DynamoDBAttribute(attributeName = "lead_owner")
	public String getLeadowner() {
		return leadowner;
	}
	public void setLeadowner(String leadowner) {
		this.leadowner = leadowner;
	}
	
	@DynamoDBRangeKey(attributeName = "tenant_id")
	public String getTenantId() {
		return tenantId;
	}
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}
	
	@DynamoDBAttribute(attributeName = "lead_company")
	public String getlCompany() {
		return lCompany;
	}
	public void setlCompany(String lCompany) {
		this.lCompany = lCompany;
	}
	
	@DynamoDBAttribute(attributeName = "lead_firstname")
	public String getlFname() {
		return lFname;
	}
	public void setlFname(String lFname) {
		this.lFname = lFname;
	}
	
	@DynamoDBAttribute(attributeName = "lead_lastname")
	public String getlLname() {
		return lLname;
	}
	public void setlLname(String lLname) {
		this.lLname = lLname;
	}
	
	@DynamoDBAttribute(attributeName = "lead_email")
	public String getlEmail() {
		return lEmail;
	}
	public void setlEmail(String lEmail) {
		this.lEmail = lEmail;
	}
	
	@DynamoDBAttribute(attributeName = "lead_workphone")
	public String getlWorkph() {
		return lWorkph;
	}
	public void setlWorkph(String lWorkph) {
		this.lWorkph = lWorkph;
	}
	
	@DynamoDBAttribute(attributeName = "lead_personalphone")
	public String getlPersonalph() {
		return lPersonalph;
	}
	public void setlPersonalph(String lPersonalph) {
		this.lPersonalph = lPersonalph;
	}
	
	@DynamoDBAttribute(attributeName = "lead_status")
	public String getlStatus() {
		return lStatus;
	}
	public void setlStatus(String lStatus) {
		this.lStatus = lStatus;
	}

}
